<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Tableau de bord',
                'updated_at' => '2020-08-05 14:51:11',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Médiathèque',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Utilisateurs',
                'updated_at' => '2020-08-05 14:51:11',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Rôles',
                'updated_at' => '2020-08-05 14:51:11',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Outils',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Créateur de menus',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Base de données',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'voyager::seeders.menu_items.compass',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:51:11',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Paramètres',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-05 14:53:01',
                'icon_class' => 'voyager-hook',
                'id' => 11,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.hooks',
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2020-08-07 16:58:50',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:53:41',
                'icon_class' => NULL,
                'id' => 12,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:53:52',
                'icon_class' => NULL,
                'id' => 13,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.faq-categories.index',
                'target' => '_self',
                'title' => 'Faq Categories',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            13 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:54:01',
                'icon_class' => NULL,
                'id' => 14,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.faqs.index',
                'target' => '_self',
                'title' => 'Faqs',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            14 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:54:11',
                'icon_class' => NULL,
                'id' => 15,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.pages.index',
                'target' => '_self',
                'title' => 'Pages',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            15 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:54:28',
                'icon_class' => NULL,
                'id' => 16,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.sous-categories.index',
                'target' => '_self',
                'title' => 'Sous Categories',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            16 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 16:54:36',
                'icon_class' => NULL,
                'id' => 17,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.temoignages.index',
                'target' => '_self',
                'title' => 'Temoignages',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-08-07 16:58:33',
                'icon_class' => 'voyager-character',
                'id' => 18,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Contenu',
                'updated_at' => '2020-08-07 17:00:52',
                'url' => '',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-08-07 17:00:02',
                'icon_class' => NULL,
                'id' => 19,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => 18,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Formations',
                'updated_at' => '2020-08-19 07:46:50',
                'url' => '/admin/formations',
            ),
            19 => 
            array (
                'color' => NULL,
                'created_at' => '2020-08-07 17:03:07',
                'icon_class' => NULL,
                'id' => 20,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 18,
                'route' => 'voyager.conseils.index',
                'target' => '_self',
                'title' => 'Conseils',
                'updated_at' => '2020-08-10 06:33:17',
                'url' => '',
            ),
            20 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-06-09 19:11:56',
                'icon_class' => NULL,
                'id' => 24,
                'menu_id' => 2,
                'order' => 10,
                'parameters' => '{
"slug":"produit1"
}',
                'parent_id' => NULL,
                'route' => 'page',
                'target' => '_self',
                'title' => 'Produit 1',
                'updated_at' => '2022-06-09 19:11:56',
                'url' => '',
            ),
        ));
        
        
    }
}